from enum import Enum


class EAccountType(str, Enum):
    CHECKING_ACCOUNT = 'CC'
    DEPOSIT_ACCOUNT = 'CD'
    ESCROW_ACCOUNT = 'CG'
    PAYMENT_ACCOUNT = 'PG'
    SAVINGS_ACCOUNT = 'PP'
    INVESTMENT_ACCOUNT = 'CI'

    def __str__(self):
        return self.value


class EDocumentType(str, Enum):
    CPF = 'cpf'
    CNPJ = 'cnpj'

    def __str__(self):
        return ' cpf' if self == EDocumentType.CPF else 'cnpj'


class EContractEffect(int, Enum):
    TITULARITY_CHANGE = 1
    GUARANTEE = 2

    def __str__(self):
        return f"{self.value}"


class EDivisionMethod(int, Enum):
    NOMINAL_VALUE = 1
    PERCENTAGE = 2

    def __str__(self):
        return f"{self.value}"


class EGuaranteeType(int, Enum):
    NO_GUARRANTEE = 0
    FIDUCIARY = 1
    PLEDGE = 2
    PROMISE_TO_PAY = 3

    def __str__(self):
        return f"{self.value}"


class EContractStatus(int, Enum):
    PENDING_REGISTRATION = 1
    ACTIVE_REGISTRATION = 2
    CANCELLED_REGISTRATION = 3
    UNABLE_TO_REGSTER = 4

    def __str__(self):
        return f"{self.value}"


class ETransaction(int, Enum):
    CONTRACT_DATA = 1
    BANK_LIQUIDATION_DATA = 2
    RECEIVABLES_UNIT_DATA = 3

    def __str__(self):
        return f"{self.value}"


class EArrangement(str, Enum):
    AMEX_CREDIT_CARD = 'ACC'
    BANESCARD_CREDIT_CARD = 'BBC'
    BANESCARD_DEBIT_CARD = 'BCD'
    BEN_VISA_VALE = 'BVV'
    CIELO_AMEX_CREDT = 'CAC'
    CABAL_CREDIT = 'CBC'
    CABAL_DEBIT = 'CBD'
    CABAL_PRE_PAID = 'CBP'
    CIELO_DINERS_CREDIT_CARD = 'CDC'
    CIELO_ELO_CREDIT_CARD = 'CEC'
    CIELO_ELO_DEBIT_CARD = 'CED'
    CIELO_HIPERCARD_CREDIT = 'CHC'
    CIELO_MASTERCARD_CREDIT = 'CMC'
    CIELO_MASTERCARD_DEBIT = 'CMD'
    CREDZ_CREDIT = 'CZC'
    DINERS_DEBIT_CARD = 'DCC'
    ELO_CREDIT_CARD = 'ECC'
    ELO_DEBIT_CARD = 'ECD'
    GOODCARD_CREDIT = 'GCC'
    GLOBAL_PAYMENTS_DINERS_CREDIT = 'GDC'
    GLOBAL_PAYMENTS_MASTERCARD_CREDIT = 'GMC'
    GLOBAL_PAYMENTS_MASTERCARD_DEBIT = 'GMD'
    GLOBAL_PAYMENTS_VISA_CREDIT = 'GVC'
    GLOBAL_PAYMENTS_VISA_DEBIT = 'GVD'
    HIPERCARD_CREDIT_CARD = 'HCC'
    JCB_CREDIT_CARD = 'JCC'
    MAIS_CREDIT_CARD = 'MAC'
    MASTERCARD_ATM_CARD = 'MCA'
    MASTERCARD_CREDIT_CARD = 'MCC'
    MASTERCARD_DEBIT_CARD = 'MCD'
    MASTERCARD_PREPAYD_CARD = 'MCP'
    OUROCARD_DEBIT_CARD = 'OCD'
    SOROCRED_CREDIT_CARD = 'SCC'
    SOROCRED_DEBIT_CARD = 'SCD'
    VISA_ATM_CARD = 'VCA'
    VISA_CREDIT_CARD = 'VCC'
    VISA_DEBIT_CARD = 'VCD'
    VISA_PREPAID_CARD = 'VCP'
    VERDECARD_CREDIT_CARD = 'VDC'
    VISA_INTERNATIONAL_PURCHASE_CREDIT = 'VIC'
    VISA_INTERNATIONAL_PURCHASE_DEBIT = 'VID'

    def __str__(self):
        return f"{self.value}"


class EBank(int, Enum):
    STONE_PAGAMENTOS = 197
    BANCO_COOPERATIVO_SICREDI_SA = 748
    ADVANCED_CC_LTDA = 117
    BANCO_INTER = 77
    NEON_PAGAMENTOS = 735
    SUPERDIGITAL = 340
    PAGBANK = 290
    BANCO_AGIBANK_SA = 121
    NEXT = 237
    BANCO_ORIGINAL = 212
    NUBANK = 260
    BANCO_WILLBANK = 280
    ALBATROSS_CCV_SA = 172
    MERCADO_PAGO = 323
    ATIVA_INVESTIMENTOS_SA = 188
    PICPAY = 380
    AVISTA_SA_CRÉDITO_FINANCIAMENTO_E_INVESTIMENTO = 280
    B_T_CC_LTDA = 80
    BANCO_AJR_ENNER_SA = 654
    BANCO_ABC_BRASIL_SA = 246
    BANCO_ABN_AMRO_SA = 75
    BANCO_AGIBANK_BRASIL_SA = 121
    BANCO_ALFA_SA = 25
    BANCO_ALVORADA_SA = 641
    BANCO_ANDBANK_BRASIL_SA = 65
    BANCO_ARBI_SA = 213
    BANCO_B3_SA = 96
    BANCO_SANTANDER = 33
    BANCO_BMG_SA = 318
    BANCO_BNP_PARIBAS_BRASIL_SA = 752
    BANCO_BOCOM_BBM_SA = 107
    BANCO_BRADESCARD_SA = 63
    CÓDIGO_BANCO_BEG_SA = 31
    BANCO_BRADESCO_BERJ_SA = 122
    BANCO_BRADESCO_CARTÕES_SA = 204
    BANCO_BRADESCO_FINANCIAMENTOS_SA = 394
    BANCO_BRADESCO_SA = 237
    BANCO_BS2_SA = 218
    BANCO_BTG_PACTUAL_SA = 208
    BANCO_C6_SA_C6_BANK = 336
    BANCO_CAIXA_GERAL_BRASIL_SA = 473
    BANCO_CAIXA_ECONÔMICA_FEDERAL = 104
    BANCO_CAPITAL_SA = 412
    BANCO_CARGILL_SA = 40
    BANCO_CARREFOUR = 368
    BANCO_CÉDULA_SA = 266
    BANCO_CETELEM_SA = 739
    BANCO_CIFRA_SA = 233
    BANCO_CITIBANK_SA = 745
    BANCO_CLÁSSICO_SA = 241
    BANCO_COOPERATIVO_DO_BRASIL_SA_BANCOOB = 756
    BANCO_CREDIT_AGRICOLE_BRASIL_SA = 222
    BANCO_CREDIT_SUISSE_BRASIL_SA = 505
    BANCO_CREFISA_SA = 69
    BANCO_DA_AMAZÔNIA_SA = 3
    BANCO_DA_CHINA_BRASIL_SA = 83
    BANCO_DAYCOVAL_SA = 707
    BANCO_DE_DESENVOLVIMENTO_DO_ESPIRITO_SANTO_SA = 51
    BANCO_DE_LA_NACION_ARGENTINA = 300
    BANCO_DE_LA_PROVINCIA_DE_BUENOS_AIRES = 495
    BANCO_DE_LA_REPUBLICA_ORIENTAL_DEL_URUGUAY = 494
    BANCO_DIGIO_SA = 335
    BANCO_DO_BRASIL_SA = 1
    BANCO_DO_ESTADO_DE_SERGIPE_SA = 47
    BANCO_DO_ESTADO_DO_PARA_SA = 37
    BANCO_DO_ESTADO_DO_RIO_GRANDE_DO_SUL_SA = 41
    BANCO_DO_NORDESTE_DO_BRASIL_SA = 4
    BANCO_FAIR_CORRETORA_DE_CÂMBIO_SA = 196
    BANCO_FATOR_SA = 265
    BANCO_FIBRA_SA = 224
    BANCO_FICSA_SA = 626
    BANCO_FINAXIS_SA = 94
    BANCO_GUANABARA_SA = 612
    BANCO_INBURSA_SA = 12
    BANCO_INDUSTRIAL_DO_BRASIL_SA = 604
    BANCO_INDUSVAL_SA = 653
    BANCO_INTER_SA = 77
    BANCO_INVESTCRED_UNIBANCO_SA = 249
    BANCO_ITAÚ_BBA_SA = 184
    BANCO_ITAÚ_CONSIGNADO_SA = 29
    BANCO_ITAUBANK_SA = 479
    BANCO_ITAÚ = 341
    BANCO_JP_MORGAN_SA = 376
    BANCO_SAFRA = 422
    BANCO_JOHN_DEERE_SA = 217
    BANCO_KDB_SA = 76
    BANCO_KEB_HANA_DO_BRASIL_SA = 757
    BANCO_LUSO_BRASILEIRO_SA = 600
    BANCO_MÁXIMA_SA = 243
    BANCO_MAXINVEST_SA = 720
    BANCO_MERCANTIL_DO_BRASIL_SA = 389
    BANCO_MIZUHO_DO_BRASIL_SA = 370
    BANCO_MODAL_SA = 746
    BANCO_MORGAN_STANLEY_SA = 66
    BANCO_MUFG_BRASIL_SA = 456
    BANCO_NACIONAL_DE_DESENVOLVIMENTO_ECONÔMICO_E_SOCIAL_BNDES = 7

    def __str__(self):
        return f"{self.value:03d}"
